language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

#matrix:
#  allow_failures:
#  - rust: beta
#  - rust: nightly

os:
  - linux

addon:
  apt:
    sources:
      - sourceline: 'ppa:mc3man/trusty-media' # For easy installing ffmpeg
    packages:
      - software-properties-common
      - gcc
      - libssl-dev
      - pkg-config
      - libopus-dev

install:
    - wget https://github.com/jedisct1/libsodium/releases/download/1.0.8/libsodium-1.0.8.tar.gz
    - tar xvfz libsodium-1.0.8.tar.gz
    - cd libsodium-1.0.8 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
        cd ..
    - export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
    - export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH

notifications:
  email: false
